### ISSUE TITLE
檔案無法開啟的情況

### ISSUE THREAD

**Issue by boyan1001** [boyan1001/boyan_csie_notebook#3]
如果大家有遇到檔案無法開啟的話  
可以嘗試**用電腦開啟**  
我發現用平板開的話有些大檔案無法打開  
   
如果用電腦還是打不開的話  
請在本討論串下跟我說一聲  
謝謝大家的配合 ^ ^

**Comment by a0966082181** [comment]
![OIP](https://github.com/user-attachments/assets/007f467f-bfac-4bb0-871c-2dccdd5148ac)
